logging: DEBUG
# API tokens
token: ".env.test"
# max number of retries to get a valid mission plan from ChatGPT
max_retries: 10
max_tokens: 10000
temperature: 0.2
log_directory: "./app/gpt_outputs/http"
# schema per 1872.1-2024 + farm layout
schema:
  - "schemas/schemas/amiga_btcpp.xsd"
context_files:
  - "./app/resources/context/wheeled_bots/reza_medium_polygon.txt"
farm_polygon:
  points:
    # start from north west corner (as best as possible)
    - lon: -120.42079453
      lat: 37.26643908
    # go clockwise
    - lon: -120.42012318
      lat: 37.26644777
    - lon: -120.42011635
      lat: 37.26578860
    - lon: -120.42079999
      lat: 37.26578751
  dimensions:
    # draw this out from top (north) to bottom (south)
    - row: 18
      col: 8
# HTTP server configuration
http_server:
  host: "127.0.0.1"
  port: 9001
# Robot communication (TCP server for sending XML missions)
host: 127.0.0.1
port: 12346
# LTL generation?
ltl: False
promela_template: "app/resources/context/formal_verification/promela_template.txt"
spin_path: "spin"