logging: DEBUG
# API tokens
token: ".env"
# max number of retries to get a valid mission plan from ChatGPT
max_retries: 10
max_tokens: 10000
temperature: 0.2
log_directory: "./app/gpt_outputs/icra"
# schema per 1872.1-2024 + farm layout
schema:
  - "schemas/schemas/clearpath_husky.xsd"
context_files:
  # - "./app/resources/context/wheeled_bots/reza20.geojson"
  - "./app/resources/context/wheeled_bots/reza.geojson"
farm_polygon:
  top_left: [-120.42079453, 37.26643908]
  top_right: [-120.42012318, 37.26644777]
  bottom_right: [-120.42011635, 37.26578860]
  bottom_left: [-120.42079999, 37.26578751]
  rows: 18
  cols: 8
# who to send this too?
host: host.docker.internal
port: 12346
# LTL generation?
ltl: False
