logging: DEBUG
# OpenAI API token
token: "~/.gpt/token.env"
# max number of retries to get a valid mission plan from ChatGPT
max_retries: 2
max_tokens: 4000
temperature: 0.2
# schema per 1872.1-2024 + farm layout
log_directory: "./app/gpt_outputs/"
schema: "./app/resources/schema.xsd"
farm_layout: "./app/resources/ucm_graph20_noreward.geojson"
# who to send this too?
host: 127.0.0.1
port: 12345